version: "3.9"

services:
  web:
    image: ghcr.io/phakphum-dev/otog-web/:latest
    networks:
      - api-gateway

  api:
    image: ghcr.io/phakphum-dev/otog-api/:latest
    networks:
      - api-gateway
    
networks:
  api-gateway:
    external: true
