services:
  web:
    image: ghcr.io/phakphum-dev/otog-web:latest
    environment:
      # https://github.com/vercel/next.js/pull/44627
      - HOSTNAME=0.0.0.0
    networks:
      - api-gateway
    env_file:
      - apps/web/.env.production
      - apps/web/.env.local

  api:
    image: ghcr.io/phakphum-dev/otog-api:latest
    networks:
      - api-gateway

networks:
  api-gateway:
    external: true
