version: '3.9'

services:
  web:
    image: ghcr.io/phakphum-dev/otog-web:latest
    environment:
      # https://github.com/vercel/next.js/pull/44627
      - HOSTNAME=0.0.0.0
    networks:
      - api-gateway

  api:
    image: ghcr.io/phakphum-dev/otog-api:latest
    networks:
      - api-gateway

networks:
  api-gateway:
    external: true
