version: '3.9'
services:
  backend:
    build: .
    image: otog-backend:latest
    container_name: otog-backend
    restart: unless-stopped
    volumes:
      - ./volumes/upload:/usr/src/app/volumes/upload:rw
      - ./docs:/usr/src/app/docs:rw
      - ./source:/usr/src/app/source:rw
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - otog-network

  postgres:
    image: postgres:14
    container_name: otog-postgres
    restart: unless-stopped
    environment:
      PGPORT: ${DB_PORT}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - otog-network

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./volumes/minio:/data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    command: server --console-address ":9001" /data
    networks:
      - otog-network

networks:
  otog-network:
    name: otog-network
